language: cpp
sudo: false

notifications:
  email: false

cache:
  directories:
  - $HOME/.cache

env:
  global:
    CACHE_DIR: $HOME/.cache
    TOOLS_DIR: $HOME/.local

matrix:
  include:
    - os: linux
      compiler: gcc
      env: CMAKE_VERSION=2.8.12.2
      addons: &libc6-i386
        apt:
          packages: ['libc6:i386']

    - os: linux
      compiler: gcc
      env: CMAKE_VERSION=3.0.2
      addons: *libc6-i386

    - os: linux
      compiler: gcc
      env: CMAKE_VERSION=3.4.1

    - os: osx
      osx_image: xcode7.1
      compiler: clang
      env: CMAKE_VERSION=2.8.12.2

    - os: osx
      osx_image: xcode7.1
      compiler: clang
      env: CMAKE_VERSION=3.0.2

    - os: osx
      osx_image: xcode7.1
      compiler: clang
      env: CMAKE_VERSION=3.4.1

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew install cmake
    fi

install:
  - cmake -P Tests/install.cmake
  - export PATH="$TOOLS_DIR/bin:$PATH"

script:
  - cmake --version
  - cmake -BTests/library/build -HTests/library
  - cmake --build Tests/library/build --target install -- DESTDIR=../install

  - cmake -BTests/executable/build-source -HTests/executable -DTest_DIR=../library
  - cmake --build Tests/executable/build-source --target install -- DESTDIR=../install

  - cmake -BTests/executable/build-built -HTests/executable -DCMAKE_PREFIX_PATH=../library/install/usr/local
  - cmake --build Tests/executable/build-built --target install -- DESTDIR=../install
