foreach(CHEETAH_VARIABLE ${CHEETAH_ENVIRONMENT})
  string(REGEX REPLACE "^([^=]+)=(.+)$" "ENV{\\1} \\2" CHEETAH_VARIABLE "${CHEETAH_VARIABLE}")
  message(STATUS "set(${CHEETAH_VARIABLE})")
  set(${CHEETAH_VARIABLE})
endforeach()

message(STATUS "execute_process(COMMAND ${CHEETAH_COMMAND} fill --quiet --odir=${CHEETAH_WORKING_DIRECTORY} ${CHEETAH_OPTIONS} ${CHEETAH_SOURCE})")
execute_process(COMMAND ${CHEETAH_COMMAND} fill --quiet --odir=${CHEETAH_WORKING_DIRECTORY} ${CHEETAH_OPTIONS} ${CHEETAH_SOURCE})
