file(MAKE_DIRECTORY "$ENV{CACHE_DIR}")
file(MAKE_DIRECTORY "$ENV{TOOLS_DIR}")

set(SOURCE "$ENV{TRAVIS_OS_NAME}-$ENV{CMAKE_VERSION}")
if ("${SOURCE}" MATCHES "linux-2\\.8\\..*")
  set(CMAKE_SOURCE "cmake-$ENV{CMAKE_VERSION}-Linux-i386.tar.gz")
elseif ("${SOURCE}" MATCHES "linux-3\\.0\\..*")
  set(CMAKE_SOURCE "cmake-$ENV{CMAKE_VERSION}-Linux-i386.tar.gz")
elseif ("${SOURCE}" MATCHES "linux-3\\..*")
  set(CMAKE_SOURCE "cmake-$ENV{CMAKE_VERSION}-Linux-x86_64.tar.gz")
elseif ("${SOURCE}" MATCHES "osx-2\\.8\\..*")
  set(CMAKE_SOURCE "cmake-$ENV{CMAKE_VERSION}-Darwin-universal.tar.gz")
elseif ("${SOURCE}" MATCHES "osx-3\\.0\\..*")
  set(CMAKE_SOURCE "cmake-$ENV{CMAKE_VERSION}-Darwin-universal.tar.gz")
elseif ("${SOURCE}" MATCHES "osx-3\\.1\\..*")
  set(CMAKE_SOURCE "cmake-$ENV{CMAKE_VERSION}-Darwin-universal.tar.gz")
elseif ("${SOURCE}" MATCHES "osx-3\\..*")
  set(CMAKE_SOURCE "cmake-$ENV{CMAKE_VERSION}-Darwin-x86_64.tar.gz")
else ()
  set(CMAKE_SOURCE "cmake-$ENV{CMAKE_VERSION}-win32-x86.zip")
endif()

if (NOT EXISTS "$ENV{CACHE_DIR}/${CMAKE_SOURCE}")
  string(REGEX REPLACE "^([0-9]+\\.[0-9]+).*$" "\\1" CMAKE_VERSION "$ENV{CMAKE_VERSION}")
  message(STATUS "Downloading https://cmake.org/files/v${CMAKE_VERSION}/${CMAKE_SOURCE}...")
  file(DOWNLOAD "https://cmake.org/files/v${CMAKE_VERSION}/${CMAKE_SOURCE}" "$ENV{CACHE_DIR}/${CMAKE_SOURCE}" INACTIVITY_TIMEOUT 2)
endif()

if ("$ENV{TRAVIS_OS_NAME}" STREQUAL "linux")
  execute_process(COMMAND tar --strip-components=1 -xf "$ENV{CACHE_DIR}/${CMAKE_SOURCE}" -C "$ENV{TOOLS_DIR}")
elseif ("$ENV{TRAVIS_OS_NAME}" STREQUAL "osx")
  execute_process(COMMAND tar --strip-components=3 -xf "$ENV{CACHE_DIR}/${CMAKE_SOURCE}" -C "$ENV{TOOLS_DIR}")
else()
  execute_process(COMMAND ${CMAKE_COMMAND} -E chdir "$ENV{TOOLS_DIR}" ${CMAKE_COMMAND} -E tar xf "$ENV{CACHE_DIR}/${CMAKE_SOURCE}")
endif()
